### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by ConradMearns** [dlrobertson/sylkie#33]
Howdy,
After installing dependencies on an Ubuntu 18.04 machine, I get the following error when attempting to run `sudo sylkie`

`
sylkie: error while loading shared libraries: libsylkie.so.0: cannot open shared object file: No such file or directory
`

I can, however, run sylkie in the build directory with `sudo ./sylkie` as libsylike.so exists there. I tried placing a symlink to libsylkie.so.0 but that didn't do the trick either, any suggestions?

**Comment by dlrobertson** [comment]
~~How did you install it?~~ Either add the directory `libsylkie.so.0` is located in to `ld.so.conf` or build the binary as a static binary with the `ENABLE_STATIC` [build option]. E.g.

```
cmake -GNinja -CCMAKE_BUILD_TYPE=Release -DENABLE_STATIC=ON ..
```

EDIT: If you're going to use it from a relative path building it as a static binary is probably your best bet.

[build option]: https://github.com/dlrobertson/sylkie/wiki#build-options

**Comment by ConradMearns** [comment]
Building as a static binary solved the issue! Thanks for the help.
